name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
      
      - name: Run tests
        run: deno test --allow-all --check --doc

      - name: Run linter
        run: deno lint
      
      - name: Run formatter
        run: deno fmt --check

      - name: Run coverage
        run: deno test --allow-all --coverage=coverage --unstable
        if: ${{ github.event_name == 'push' }}